kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cache-imagewarm
rules:
  - apiGroups: [""]
    resources: ["configmaps", "services", "secrets", "events", "pods"]
    verbs: ["get", "list", "create", "update", "delete", "patch", "watch"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "list", "create", "update", "delete", "patch", "watch"]
  - apiGroups: ["admissionregistration.k8s.io"]
    resources: ["mutatingwebhookconfigurations", "validatingwebhookconfigurations"]
    verbs: ["get", "list", "create", "update", "delete", "patch", "watch"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "list", "create", "update", "delete", "patch", "watch"]
  - apiGroups: ["caching.knative.dev"]
    resources: ["*"]
    verbs: ["get", "list", "create", "update", "delete", "deletecollection", "patch", "watch"]
  - apiGroups: [ "caching.internal.knative.dev" ]
    resources: [ "*" ]
    verbs: [ "get", "list", "create", "update", "delete", "deletecollection", "patch", "watch" ]
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cache-controller
rules:
  - apiGroups: [""]
    resources: ["configmaps", "services", "secrets", "events", "pods"]
    verbs: ["get", "list", "create", "update", "delete", "patch", "watch"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "list", "create", "update", "delete", "patch", "watch"]
  - apiGroups: ["admissionregistration.k8s.io"]
    resources: ["mutatingwebhookconfigurations", "validatingwebhookconfigurations"]
    verbs: ["get", "list", "create", "update", "delete", "patch", "watch"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "list", "create", "update", "delete", "patch", "watch"]
  - apiGroups: ["caching.knative.dev"]
    resources: ["*"]
    verbs: ["get", "list", "create", "update", "delete", "deletecollection", "patch", "watch"]
  - apiGroups: [ "caching.internal.knative.dev" ]
    resources: [ "*" ]
    verbs: [ "get", "list", "create", "update", "delete", "deletecollection", "patch", "watch" ]
